# Generated by Django 5.2.3 on 2026-08-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='External Link'),
        ),
    ]
