# Generated by Django 5.2.3 on 2026-08-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0004_post_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Title/Caption'),
        ),
    ]
